### ISSUE TITLE
Add versioning specification for web fonts?

### ISSUE THREAD

**Issue by chrissimpkins** [openfv/openfv#1]
Addendum: Didn't provide details as basis for this conversation.  See https://github.com/openfv/openfv/issues/1#issuecomment-354843065

**Comment by chrissimpkins** [comment]
Specify as part of the CSS file URL strings for web fonts?

**Comment by pathumego** [comment]
Could you explain this?

**Comment by chrissimpkins** [comment]
The intent here is to determine if it would be appropriate to include a standard for versioning information in web font build CSS files.  We are currently using a git commit SHA1 hash in the CSS web font URL for Hack web fonts.  I am wondering if we can develop an approach that leads to explicit versioning information for web fonts (for both users and developers) that is exposed in an easy to interpret fashion without examination of the web font binaries.

**Comment by pathumego** [comment]
It is a needed feature. But isn't is more of a `web font packaging standards` concern? In this case the CSS file spec will also becomes a part of this spec right?

**Comment by chrissimpkins** [comment]
Yes that would be the case.  Thoughts about how to incorporate web fonts into the spec here?

**Comment by chrissimpkins** [comment]
@davelab6 How are you approaching this on Google Fonts?  Does versioning from the original source extend to the CSS files that are being served?

**Comment by chrissimpkins** [comment]
Here is a sample from the Roboto Google Fonts CSS that is served up to me:

```CSS
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v18/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2212, U+2215;
}
```

**Comment by chrissimpkins** [comment]
My thought was to harness the URL path along the lines that they are doing here (maybe?):

```
roboto/v18/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2
```

but specify query strings to capture the information.  There would be no re-specification of CSS if that is what you are getting at.  Only using standard URL query strings that would contain the version, state, status data that we describe in this spec.

Something along these lines:

```css
/* latin */
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  src: local('SomeFont'), local('SomeFont-Regular'), url(https://fonts.somewhere.org/somefont/somefont.woff2?v=1.010&state=abcd123&status=dev) format('woff2');
}
```
